### ISSUE TITLE
Auto-select a single workspace

### ISSUE THREAD

**Issue by mbaas2** [tobiaswaelde/vscode-clockify#11]
Hi Tobias - this looks like a useful project - thank you!
After installing (and entering my API-Key) I was confused that Clients/Projects etc. were empty and it took me the best part of a minute to notice that I have to activate my workspace first (dbl-click). Since I only have one (as most users, I assume) it would be nice (and save some confusion) if a sole workspace was activated by default :)

**Comment by tobiaswaelde** [comment]
Thank you for your feedback. I am currently working on v4 where it will be shown which workspace is currently selected.
