### ISSUE TITLE
Simpler start/stop

### ISSUE THREAD

**Issue by hazg** [tobiaswaelde/vscode-clockify#19]
Is there a way to do the same in the plugin?

I am currently using ***fabiospampinato.vscode-commands*** to make the counter start and stop

commands.json
``` json
{
  "commands": [
    {
      "command": "clockify.tracking.stop",
      "alignment": "right",
      "text": "$(primitive-square)",
      "tooltip": "Stop clockify",
      "color": "#ff0000"
    },
    {
      "command": "clockify.tracking.start",
      "alignment": "right",
      "text": "$(triangle-right)",
      "tooltip": "Start clockify",
      "color": "#10f009"
    } 
  
  ]
}
```

looks like this:
![Screenshot from 2021-06-22 09:13:54](https://user-images.githubusercontent.com/178218/122873393-602c1e00-d33a-11eb-8a1a-d56cc6022c66.png)

**Comment by BrianGilbert** [comment]
I found aligning these to the left instead of right was a bit better for me.

**Comment by dmcrider** [comment]
Where does that live?

**Comment by tobiaswaelde** [comment]
Thank you for your feedback. That's a great idea and I will add this feature in v4 (currently work in progress)
