### ISSUE TITLE
Text is not visible in status bar

### ISSUE THREAD

**Issue by irajeshh** [tobiaswaelde/vscode-clockify#29]
When vscode is ideal, the text is in green color, so this is not visible
![1](https://user-images.githubusercontent.com/85046336/175756628-b3960288-c51c-4471-97bd-4c1da8e98c13.png)

When debuggin is started, the text color becomes red, and this time also not visible.
![2](https://user-images.githubusercontent.com/85046336/175756629-777b5155-0123-44f1-b505-18bb2f85e0d6.png)

**Comment by tobiaswaelde** [comment]
In v4 (currently work in progress) the text will have the default color
