### ISSUE TITLE
Add quick toggle button to statusbar

### ISSUE THREAD

**Issue by evertiro** [tobiaswaelde/vscode-clockify#3]
It'd be nice if the existing statusbar icon toggled the timer. I've been working on tweaking the extension to add it myself, and have successfully made it start a timer, but I'm struggling at the moment with detecting state to allow it to stop a running timer. Seems I can't access `context` from within the `openStatusBarMenu()` function and I haven't been able to figure out how to add it... yet.

**Comment by azertyalex** [comment]
Can't you do
```Javascript
context.subscriptions.push(
     vscode.commands.registerCommand('clockify.statusbar.menu', () => openStatusBarMenu(context))
);
```

And change the openStatusBarMenu definition to
`export function openStatusBarMenu(context:vscode.ExtensionContext)` ?

**Comment by evertiro** [comment]
Tried basically that, and tried this as well:

```context.subscriptions.push(vscode.commands.registerCommand('clockify.statusbar.menu', () => {
    openStatusBarMenu(context);
}));```

Neither worked (both throw `TypeError: Cannot read property 'globalState' of undefined`). I'll admit, I'm _way_ out of my depth trying to work with Node 😛

**Comment by azertyalex** [comment]
If you want look at my fork of the plugin. But for now it's only workable in dev mode.

**Comment by tobiaswaelde** [comment]
As mentioned in #19 I am working on it. Version 4 of the extension is coming soon :)
