### ISSUE TITLE
Project not found in list, but archived projects are

### ISSUE THREAD

**Issue by MatMorrisParker** [tobiaswaelde/vscode-clockify#30]
After selecting to start the timer and selecting the workspace, the list of projects doesn't show all the projects on the account.

Our projects are numbered "Jxxxx", for example, J0472, J0175. Anything past J0499 isn't shown.

However, out of the projects being shown in the list, there are archived projects also showing, which I wouldn't expect to be shown. Is this intended?

**Comment by tobiaswaelde** [comment]
Thank you for your feedback.
This is an issue in the current data fecthing function which fetches only 100 (i I think) projects.
I am currently working on v4 (see the 'next' branch) where you will have many more configuration options. You will be able to set the fetching limit on your own and an option to show/hide archived projects and many more
