### ISSUE TITLE
Release a new version on the VsCode marketplace

### ISSUE THREAD

**Issue by aminya** [tobiaswaelde/vscode-clockify#31]
The latest version on the marketplace is 3.0.12, while I see [3.0.14](https://github.com/tobiaswaelde/vscode-clockify/commit/c5d5bdeef06807500fde7554429ed1d0cad23042) in the commit history
https://marketplace.visualstudio.com/items?itemName=tobiaswaelde.clockify-tracker

**Comment by tobiaswaelde** [comment]
I had issues with my extension account. As I am currently working on v4, no more updates on v3 will be published.
v4 will launch soon :)
