### ISSUE TITLE
Clockify: Start Tracking is not coming up as a command

### ISSUE THREAD

**Issue by Arkyris** [tobiaswaelde/vscode-clockify#40]
I have a workspace linked with the API key, client, project and task all showing. But when I pull up the drop down with CTRL+SHIFT+P the start tracking command is no where to be found. Im in vs code, and downloaded through the extensions page.

**Comment by tobiaswaelde** [comment]
I start working on it ASAP. Until then, you can use the icon in the status bar

**Comment by Arkyris** [comment]
Thank you, I didn't even notice the status bar. That also seems un-responsive. I've just been starting the time on the website for now. I just found this today, really appreciate what you're doing
