### ISSUE TITLE
Auto-Tracking

### ISSUE THREAD

**Issue by DanielHabenicht** [tobiaswaelde/vscode-clockify#5]
First of all, great extension! This is just an idea, that popped into my mind I thought would be worth sharing. (I don't have time to program it, neither do I suspect anybody else has.) 

It would be great if the extension could automatically track which project I am working on, based on the project opened. 

First of it would be great if "workspace" and "project" could be automatically selected based on the workspace the user currently has open. 

Later on, something like automatic tracking based on commits could be added.

**Comment by Yazir** [comment]
It could work as wakatime does.

**Comment by tobiaswaelde** [comment]
I am currently working on an own time tracker like waka time.
It's not yet finished and will take a few weeks to but if you want to get it, check code-time.tobiaswaelde.com periodically.

**Comment by gino8080** [comment]
> I am currently working on an own time tracker like waka time.
> It's not yet finished and will take a few weeks to but if you want to get it, check[ code-time.tobiaswaelde.com](code-time.tobiaswaelde.com) periodically.

I would really interested on partecipate development if you want!

but the link is wrong

btw also the code-time.tobiaswaelde.com url show nothing

**Comment by tobiaswaelde** [comment]
I really could need some help 😄 
please contact me via email, whatsapp or telegram. you can find my contact information here: [tobiaswaelde.com](tobiaswaelde.com)

**Comment by Yazir** [comment]
Code 406 if you click on the link you've posted. https://info.tobiaswaelde.com this link should work fine.

And refering to the code-time. There is already a handy extension called like that from _Software_:
https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode

Is there any affiliation with that extension or its a coincidence?

**Comment by tobiaswaelde** [comment]
you should be automatically redirected to info.tobiaswaelde.com

i already know the extension from _Software_, but i miss some features (which exist in waka time). But i do not want to waste 10$ per month just to show more than the last 14 days. So i prefer to build my own extension.
Due to my coding habits (coding on the backseat while traveling long distances) where I do not always have an internet connection I want to build mine almost completely independent.

**Comment by oryon-dominik** [comment]
Hey Tobias, do you need help on this?

**Comment by tobiaswaelde** [comment]
@DanielHabenicht Currently you can create a `.vscode/settings.json` inside your project root where you can set the default workspace ID and default project ID. This should help until v4 is finished where these functions should be simplified and accessible via the context menu in the tree view.
