### ISSUE TITLE
Add an option to hide archived Projects and Clients

### ISSUE THREAD

**Issue by stefanobartoletti** [tobiaswaelde/vscode-clockify#8]
In order to declutter the interface, especially in the explorer but also from the command palette, I think it would be useful to have an option to hide archived items, like Projects and Clients.

This would improve the user experience, IMHO.

**Comment by BrianGilbert** [comment]
Yes, the extension needs this please

**Comment by rattkin** [comment]
i also don't see all the projects. I see only about first 50 of them

**Comment by rattkin** [comment]
made a PR https://github.com/tobiaswaelde/vscode-clockify/pull/23

**Comment by tobiaswaelde** [comment]
merged, update will be available soon

**Comment by tobiaswaelde** [comment]
My vsce account seems to be resetted...
I can still access my organization but all projects are gone.

**Comment by rattkin** [comment]
sorry to hear that!
are you planning to re-release it?

**Comment by tobiaswaelde** [comment]
I have a lot of work to do right now.
But I definitely try to fix that issues soon.
If I am not able to find my old extensions, I will re-release them all.
